[project]
name = 'smart-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.autostack-goals]
path = 'contracts/autostack-goals.clar'
clarity_version = 3
epoch = 3.1

[contracts.autostack-rewards]
path = 'contracts/autostack-rewards.clar'
clarity_version = 3
epoch = 3.1

[contracts.autostack-savings]
path = 'contracts/autostack-savings.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
